USE [master]
GO

/****** Object:  Database [BdPedidos]    Script Date: 5/7/2021 19:32:58 ******/
CREATE DATABASE [BdPedidos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BdPedidos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BdPedidos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BdPedidos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BdPedidos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BdPedidos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BdPedidos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BdPedidos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BdPedidos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BdPedidos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BdPedidos] SET ARITHABORT OFF 
GO

ALTER DATABASE [BdPedidos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BdPedidos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BdPedidos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BdPedidos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BdPedidos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BdPedidos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BdPedidos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BdPedidos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BdPedidos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BdPedidos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BdPedidos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BdPedidos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BdPedidos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BdPedidos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BdPedidos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BdPedidos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BdPedidos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BdPedidos] SET RECOVERY FULL 
GO

ALTER DATABASE [BdPedidos] SET  MULTI_USER 
GO

ALTER DATABASE [BdPedidos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BdPedidos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BdPedidos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BdPedidos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BdPedidos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BdPedidos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BdPedidos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BdPedidos] SET  READ_WRITE 
GO


